# Generated by Django 5.2.6 on 2025-09-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='description',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
